{"lang":"dockerfile","variants":[
{"r":[0,42],"rows":["4k 8d 1n","3k 24d",""]},
{"r":[0,42],"rows":["4k 8d 1n","3k 24d",""]},
{"r":[25,36],"rows":["11d"]},
{"r":[0,40],"rows":["4k 8d 1n","3k 23d"]}
]}
