// OWNER: syntax (generated from grok-night.tmTheme of xai-org/grok-build, Apache-2.0)
//! The scope rules of Grok Build's `grok-night.tmTheme` as data: (scope selector, foreground,
//! font style). `ui::syntax` turns them into a syntect `Theme`. Default foreground `#b2b2b2`.

pub const DEFAULT_FG: u32 = 0xb2b2b2;

pub const RULES: &[(&str, Option<u32>, Option<&str>)] = &[
    ("comment, meta.var.expr storage.type, keyword.control.flow, keyword.control.return, meta.directive.vue punctuation.separator.key-value.html, meta.directive.vue entity.other.attribute-name.html, tag.decorator.js entity.name.tag.js, tag.decorator.js punctuation.definition.tag.js, storage.modifier, string.quoted.docstring.multi, string.quoted.docstring.multi.python punctuation.definition.string.begin, string.quoted.docstring.multi.python punctuation.definition.string.end, string.quoted.docstring.multi.python constant.character.escape", None, Some("italic")),
    ("keyword.control.flow.block-scalar.literal, keyword.control.flow.python", None, Some("")),
    ("comment, comment.block.documentation, punctuation.definition.comment, comment.block.documentation punctuation, string.quoted.docstring.multi, string.quoted.docstring.multi.python punctuation.definition.string.begin, string.quoted.docstring.multi.python punctuation.definition.string.end, string.quoted.docstring.multi.python constant.character.escape", Some(0x51597d), None),
    ("keyword.operator.assignment.jsdoc, comment.block.documentation variable, comment.block.documentation storage, comment.block.documentation keyword, comment.block.documentation support, comment.block.documentation markup, comment.block.documentation markup.inline.raw.string.markdown, meta.other.type.phpdoc.php keyword.other.type.php, meta.other.type.phpdoc.php support.other.namespace.php, meta.other.type.phpdoc.php punctuation.separator.inheritance.php, meta.other.type.phpdoc.php support.class, keyword.other.phpdoc.php, log.date", Some(0x5a638c), None),
    ("meta.other.type.phpdoc.php support.class, comment.block.documentation storage.type, comment.block.documentation punctuation.definition.block.tag, comment.block.documentation entity.name.type.instance", Some(0x646e9c), None),
    ("variable.other.constant, punctuation.definition.constant, constant.language, constant.numeric, support.constant, constant.other.caps", Some(0xff9e64), None),
    ("string, constant.other.symbol, constant.other.key, meta.attribute-selector, string constant.character", Some(0x9ece6a), Some("")),
    ("constant.other.color, constant.other.color.rgb-value.hex punctuation.definition.constant", Some(0x9aa5ce), None),
    ("invalid, invalid.illegal", Some(0xff5370), None),
    ("invalid.deprecated", Some(0xbb9af7), None),
    ("storage.type", Some(0xbb9af7), None),
    ("meta.var.expr storage.type, storage.modifier", Some(0x9d7cd8), None),
    ("punctuation.definition.template-expression, punctuation.section.embedded, meta.embedded.line.tag.smarty, support.constant.handlebars, punctuation.section.tag.twig", Some(0x7dcfff), None),
    ("keyword.control.smarty, keyword.control.twig, support.constant.handlebars keyword.control, keyword.operator.comparison.twig, keyword.blade, entity.name.function.blade, meta.tag.blade keyword.other.type.php", Some(0x0db9d7), None),
    ("keyword.operator.spread, keyword.operator.rest", Some(0xf7768e), Some("bold")),
    ("keyword.operator, keyword.control.as, keyword.other, keyword.operator.bitwise.shift, punctuation, expression.embbeded.vue punctuation.definition.tag, text.html.twig meta.tag.inline.any.html, meta.tag.template.value.twig meta.function.arguments.twig, meta.directive.vue punctuation.separator.key-value.html, punctuation.definition.constant.markdown, punctuation.definition.string, punctuation.support.type.property-name, text.html.vue-html meta.tag, meta.attribute.directive, punctuation.definition.keyword, punctuation.terminator.rule, punctuation.definition.entity, punctuation.separator.inheritance.php, keyword.other.template, keyword.other.substitution, entity.name.operator, meta.property-list punctuation.separator.key-value, meta.at-rule.mixin punctuation.separator.key-value, meta.at-rule.function variable.parameter.url, meta.embedded.inline.phpx punctuation.definition.tag.begin.html, meta.embedded.inline.phpx punctuation.definition.tag.end.html", Some(0x89ddff), None),
    ("keyword.control.module.js, keyword.control.import, keyword.control.export, keyword.control.from, keyword.control.default, meta.import keyword.other", Some(0x7dcfff), None),
    ("keyword, keyword.control, keyword.other.important", Some(0xbb9af7), None),
    ("keyword.other.DML", Some(0x7dcfff), None),
    ("keyword.operator.logical, storage.type.function, keyword.operator.bitwise, keyword.operator.ternary, keyword.operator.comparison, keyword.operator.relational, keyword.operator.or.regexp", Some(0xbb9af7), None),
    ("entity.name.tag", Some(0xf7768e), None),
    ("entity.name.tag support.class.component, meta.tag.custom entity.name.tag, meta.tag.other.unrecognized.html.derivative entity.name.tag, meta.tag", Some(0xde5971), None),
    ("punctuation.definition.tag, text.html.php meta.embedded.block.html meta.tag.metadata.script.end.html punctuation.definition.tag.begin.html text.html.basic", Some(0xba3c97), None),
    ("constant.other.php, variable.other.global.safer, variable.other.global.safer punctuation.definition.variable, variable.other.global, variable.other.global punctuation.definition.variable, constant.other", Some(0xe0af68), None),
    ("variable, support.variable, string constant.other.placeholder, variable.parameter.handlebars, variable.other.object, meta.fstring, meta.function-call meta.function-call.arguments, meta.embedded.inline.phpx constant.other.php", Some(0xc8c8c8), None),
    ("meta.array.literal variable", Some(0x7dcfff), None),
    ("meta.object-literal.key, entity.name.type.hcl, string.alias.graphql, string.unquoted.graphql, string.unquoted.alias.graphql, meta.group.braces.curly constant.other.object.key.js string.unquoted.label.js, meta.field.declaration.ts variable.object.property, meta.block entity.name.label", Some(0x73daca), None),
    ("variable.other.property, support.variable.property, support.variable.property.dom, meta.function-call variable.other.object.property", Some(0x7dcfff), None),
    ("variable.other.object.property", Some(0xc8c8c8), None),
    ("meta.objectliteral meta.object.member meta.objectliteral meta.object.member meta.objectliteral meta.object.member meta.object-literal.key", Some(0x41a6b5), None),
    ("source.cpp meta.block variable.other", Some(0xf7768e), None),
    ("support.other.variable", Some(0xf7768e), None),
    ("meta.class-method.js entity.name.function.js, entity.name.method.js, variable.function.constructor, keyword.other.special-method, storage.type.cs", Some(0x7aa2f7), None),
    ("entity.name.function, variable.other.enummember, meta.function-call, meta.function-call entity.name.function, variable.function, meta.definition.method entity.name.function, meta.object-literal entity.name.function", Some(0x7aa2f7), None),
    ("variable.parameter.function.language.special, variable.parameter, meta.function.parameters punctuation.definition.variable, meta.function.parameter variable", Some(0xe0af68), None),
    ("keyword.other.type.php, storage.type.php, constant.character, constant.escape, keyword.other.unit", Some(0xbb9af7), None),
    ("meta.definition.variable variable.other.constant, meta.definition.variable variable.other.readwrite, variable.declaration.hcl variable.other.readwrite.hcl, meta.mapping.key.hcl variable.other.readwrite.hcl, variable.other.declaration", Some(0xbb9af7), None),
    ("entity.other.inherited-class", Some(0xbb9af7), Some("")),
    ("support.class, support.type, variable.other.readwrite.alias, support.orther.namespace.use.php, meta.use.php, support.other.namespace.php, support.type.sys-types, support.variable.dom, support.constant.math, support.type.object.module, support.constant.json, entity.name.namespace, meta.import.qualifier, variable.other.constant.object", Some(0x0db9d7), None),
    ("entity.name", Some(0xc8c8c8), None),
    ("support.function", Some(0x0db9d7), None),
    ("source.css support.type.property-name, source.sass support.type.property-name, source.scss support.type.property-name, source.less support.type.property-name, source.stylus support.type.property-name, source.postcss support.type.property-name, support.type.property-name.css, support.type.vendored.property-name, support.type.map.key", Some(0x7aa2f7), None),
    ("support.constant.font-name, meta.definition.variable", Some(0x9ece6a), None),
    ("entity.other.attribute-name.class, meta.at-rule.mixin.scss entity.name.function.scss", Some(0x9ece6a), None),
    ("entity.other.attribute-name.id", Some(0xfc7b7b), None),
    ("entity.name.tag.css", Some(0x0db9d7), None),
    ("entity.other.attribute-name.pseudo-class punctuation.definition.entity, entity.other.attribute-name.pseudo-element punctuation.definition.entity, entity.other.attribute-name.class punctuation.definition.entity, entity.name.tag.reference", Some(0xe0af68), None),
    ("meta.property-list", Some(0x9abdf5), None),
    ("meta.property-list meta.at-rule.if, meta.at-rule.return variable.parameter.url, meta.property-list meta.at-rule.else", Some(0xff9e64), None),
    ("entity.other.attribute-name.parent-selector-suffix punctuation.definition.entity.css", Some(0x73daca), None),
    ("meta.property-list meta.property-list", Some(0x9abdf5), None),
    ("meta.at-rule.mixin keyword.control.at-rule.mixin, meta.at-rule.include entity.name.function.scss, meta.at-rule.include keyword.control.at-rule.include", Some(0xbb9af7), None),
    ("keyword.control.at-rule.include punctuation.definition.keyword, keyword.control.at-rule.mixin punctuation.definition.keyword, meta.at-rule.include keyword.control.at-rule.include, keyword.control.at-rule.extend punctuation.definition.keyword, meta.at-rule.extend keyword.control.at-rule.extend, entity.other.attribute-name.placeholder.css punctuation.definition.entity.css, meta.at-rule.media keyword.control.at-rule.media, meta.at-rule.mixin keyword.control.at-rule.mixin, meta.at-rule.function keyword.control.at-rule.function, keyword.control punctuation.definition.keyword", Some(0x9d7cd8), None),
    ("meta.property-list meta.at-rule.include", Some(0xc8c8c8), None),
    ("support.constant.property-value", Some(0xff9e64), None),
    ("entity.name.module.js, variable.import.parameter.js, variable.other.class.js", Some(0xc8c8c8), None),
    ("variable.language", Some(0xf7768e), None),
    ("variable.other punctuation.definition.variable", Some(0xc8c8c8), None),
    ("source.js constant.other.object.key.js string.unquoted.label.js, variable.language.this punctuation.definition.variable, keyword.other.this", Some(0xf7768e), None),
    ("entity.other.attribute-name, text.html.basic entity.other.attribute-name.html, text.html.basic entity.other.attribute-name", Some(0xbb9af7), None),
    ("text.html constant.character.entity", Some(0x0DB9D7), None),
    ("entity.other.attribute-name.id.html, meta.directive.vue entity.other.attribute-name.html", Some(0xbb9af7), None),
    ("source.sass keyword.control", Some(0x7aa2f7), None),
    ("entity.other.attribute-name.pseudo-class, entity.other.attribute-name.pseudo-element, entity.other.attribute-name.placeholder, meta.property-list meta.property-value", Some(0xbb9af7), None),
    ("markup.inserted", Some(0x449dab), None),
    ("markup.deleted", Some(0x914c54), None),
    ("markup.changed", Some(0x6183bb), None),
    ("string.regexp", Some(0xb4f9f8), None),
    ("punctuation.definition.group", Some(0xf7768e), None),
    ("constant.other.character-class.regexp", Some(0xbb9af7), None),
    ("constant.other.character-class.set.regexp, punctuation.definition.character-class.regexp", Some(0xe0af68), None),
    ("keyword.operator.quantifier.regexp", Some(0x89ddff), None),
    ("constant.character.escape.backslash", Some(0xc8c8c8), None),
    ("constant.character.escape", Some(0x89ddff), None),
    ("tag.decorator.js entity.name.tag.js, tag.decorator.js punctuation.definition.tag.js", Some(0x7aa2f7), None),
    ("keyword.other.unit", Some(0xf7768e), None),
    ("source.json meta.structure.dictionary.json support.type.property-name.json", Some(0x7aa2f7), None),
    ("source.json meta.structure.dictionary.json meta.structure.dictionary.value.json meta.structure.dictionary.json support.type.property-name.json", Some(0x0db9d7), None),
    ("source.json meta.structure.dictionary.json meta.structure.dictionary.value.json meta.structure.dictionary.json meta.structure.dictionary.value.json meta.structure.dictionary.json support.type.property-name.json", Some(0x7dcfff), None),
    ("source.json meta.structure.dictionary.json meta.structure.dictionary.value.json meta.structure.dictionary.json meta.structure.dictionary.value.json meta.structure.dictionary.json meta.structure.dictionary.value.json meta.structure.dictionary.json support.type.property-name.json", Some(0xbb9af7), None),
    ("source.json meta.structure.dictionary.json meta.structure.dictionary.value.json meta.structure.dictionary.json meta.structure.dictionary.value.json meta.structure.dictionary.json meta.structure.dictionary.value.json meta.structure.dictionary.json meta.structure.dictionary.value.json meta.structure.dictionary.json support.type.property-name.json", Some(0xe0af68), None),
    ("source.json meta.structure.dictionary.json meta.structure.dictionary.value.json meta.structure.dictionary.json meta.structure.dictionary.value.json meta.structure.dictionary.json meta.structure.dictionary.value.json meta.structure.dictionary.json meta.structure.dictionary.value.json meta.structure.dictionary.json meta.structure.dictionary.value.json meta.structure.dictionary.json support.type.property-name.json", Some(0x0db9d7), None),
    ("source.json meta.structure.dictionary.json meta.structure.dictionary.value.json meta.structure.dictionary.json meta.structure.dictionary.value.json meta.structure.dictionary.json meta.structure.dictionary.value.json meta.structure.dictionary.json meta.structure.dictionary.value.json meta.structure.dictionary.json meta.structure.dictionary.value.json meta.structure.dictionary.json meta.structure.dictionary.value.json meta.structure.dictionary.json support.type.property-name.json", Some(0x73daca), None),
    ("source.json meta.structure.dictionary.json meta.structure.dictionary.value.json meta.structure.dictionary.json meta.structure.dictionary.value.json meta.structure.dictionary.json meta.structure.dictionary.value.json meta.structure.dictionary.json meta.structure.dictionary.value.json meta.structure.dictionary.json meta.structure.dictionary.value.json meta.structure.dictionary.json meta.structure.dictionary.value.json meta.structure.dictionary.json meta.structure.dictionary.value.json meta.structure.dictionary.json support.type.property-name.json", Some(0xf7768e), None),
    ("source.json meta.structure.dictionary.json meta.structure.dictionary.value.json meta.structure.dictionary.json meta.structure.dictionary.value.json meta.structure.dictionary.json meta.structure.dictionary.value.json meta.structure.dictionary.json meta.structure.dictionary.value.json meta.structure.dictionary.json meta.structure.dictionary.value.json meta.structure.dictionary.json meta.structure.dictionary.value.json meta.structure.dictionary.json meta.structure.dictionary.value.json meta.structure.dictionary.json meta.structure.dictionary.value.json meta.structure.dictionary.json support.type.property-name.json", Some(0x9ece6a), None),
    ("punctuation.definition.list_item.markdown", Some(0x9abdf5), None),
    ("meta.block, meta.brace, punctuation.definition.block, punctuation.definition.use, punctuation.definition.class, punctuation.definition.begin.bracket, punctuation.definition.end.bracket, punctuation.definition.switch-expression.begin.bracket, punctuation.definition.switch-expression.end.bracket, punctuation.definition.section.switch-block.begin.bracket, punctuation.definition.section.switch-block.end.bracket, punctuation.definition.group.shell, punctuation.definition.parameters, punctuation.definition.arguments, punctuation.definition.dictionary, punctuation.definition.array, punctuation.section", Some(0x9abdf5), None),
    ("meta.embedded.block", Some(0xc8c8c8), None),
    ("meta.tag JSXNested, meta.jsx.children, text.html, text.log", Some(0x9aa5ce), None),
    ("text.html.markdown markup.inline.raw.markdown", Some(0xbb9af7), None),
    ("text.html.markdown markup.inline.raw.markdown punctuation.definition.raw.markdown", Some(0x4E5579), None),
    ("heading.1.markdown entity.name, heading.1.markdown punctuation.definition.heading.markdown", Some(0x89ddff), Some("bold")),
    ("heading.2.markdown entity.name, heading.2.markdown punctuation.definition.heading.markdown", Some(0x61bdf2), Some("bold")),
    ("heading.3.markdown entity.name, heading.3.markdown punctuation.definition.heading.markdown", Some(0x7aa2f7), Some("bold")),
    ("heading.4.markdown entity.name, heading.4.markdown punctuation.definition.heading.markdown", Some(0x6d91de), Some("bold")),
    ("heading.5.markdown entity.name, heading.5.markdown punctuation.definition.heading.markdown", Some(0x9aa5ce), Some("bold")),
    ("heading.6.markdown entity.name, heading.6.markdown punctuation.definition.heading.markdown", Some(0x747ca1), Some("bold")),
    ("markup.italic, markup.italic punctuation", Some(0xc8c8c8), Some("italic")),
    ("markup.bold, markup.bold punctuation", Some(0xc8c8c8), Some("bold")),
    ("markup.bold markup.italic, markup.bold markup.italic punctuation", Some(0xc8c8c8), Some("bold italic")),
    ("markup.underline, markup.underline punctuation", None, Some("underline")),
    ("markup.quote punctuation.definition.blockquote.markdown", Some(0x4e5579), None),
    ("markup.quote", None, Some("italic")),
    ("string.other.link, markup.underline.link, constant.other.reference.link.markdown, string.other.link.description.title.markdown", Some(0x73daca), None),
    ("markup.fenced_code.block.markdown, markup.inline.raw.string.markdown, variable.language.fenced.markdown", Some(0x89ddff), None),
    ("meta.separator", Some(0x51597d), Some("bold")),
    ("markup.table", Some(0xc0cefc), None),
    ("token.info-token", Some(0x0db9d7), None),
    ("token.warn-token", Some(0xffdb69), None),
    ("token.error-token", Some(0xdb4b4b), None),
    ("token.debug-token", Some(0xb267e6), None),
    ("entity.tag.apacheconf", Some(0xf7768e), None),
    ("meta.preprocessor", Some(0x73daca), None),
    ("source.env", Some(0x7aa2f7), None),
];
